version: '3.8'

services:
  app:
    image: enhanced-authentication-service-image
    container_name: enhanced-authentication-service-container
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
